version: "3.9"

services:
  app:
    # image: php:8.2-apache を build: . に変更します
    # これにより、同じディレクトリにある Dockerfile を使ってイメージがビルドされます
    build: .
    container_name: lamp-app
    ports:
      - "80:80"
    volumes:
      # ソースコード (./src) と Apache 設定ファイル (./apache-config.conf) は
      # ビルド時に Dockerfile によってイメージにコピーされるため、ここからは削除します。

      # ./php-data ボリュームは、コンテナが書き込むデータを永続化するために残します。
      - ./php-data:/var/www/html/data

    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=testdb
      - PHP_WRITE_DIR=/var/www/html/data

  db:
    image: mysql:8.0
    container_name: lamp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
